/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * API Documentation
 * API for my project
 * OpenAPI spec version: v1
 */

export interface CommentCount {
  /** 댓글 개수 */
  count: number;
  /** 스팸 댓글 개수 */
  spam_count: number;
  /** 스팸이 아닌 댓글 개수 */
  not_spam_count: number;
  /** AI 분류가 완료되지 않은 댓글 개수 */
  unprocessed_count: number;
  /** 에피소드 ID */
  episode_id: number;
}
