/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * API Documentation
 * API for my project
 * OpenAPI spec version: v1
 */
import type { CommentsSummarySourceComments } from './commentsSummarySourceComments';

export interface CommentsSummary {
  readonly id?: number;
  source_comments: CommentsSummarySourceComments;
  /** @minLength 1 */
  readonly summary?: string;
  readonly created_at?: string;
  episode: number;
}
