/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * API Documentation
 * API for my project
 * OpenAPI spec version: v1
 */

/**
 * @nullable
 */
export type CommentEmoticon = { [key: string]: unknown } | null;
