/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * API Documentation
 * API for my project
 * OpenAPI spec version: v1
 */
import type { CommentEmoticon } from './commentEmoticon';

export interface Comment {
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  id: number;
  /** @minLength 1 */
  content: string;
  created_at: string;
  is_best: boolean;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  like_count?: number;
  /** @nullable */
  emoticon?: CommentEmoticon;
  /**
   * @minLength 1
   * @maxLength 100
   */
  user_name: string;
  /** @minLength 1 */
  user_thumbnail_url: string;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  user_uid: number;
  /**
   * @maxLength 100
   * @nullable
   */
  ai_category?: string | null;
  /** @nullable */
  ai_reason?: string | null;
  is_ai_processed?: boolean;
  /** @nullable */
  ai_processed_at?: string | null;
  series: number;
  episode: number;
}
