/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * API Documentation
 * API for my project
 * OpenAPI spec version: v1
 */

export type CrawlerSeriesListParams = {
/**
 * Number of results to return per page.
 */
limit?: number;
/**
 * The initial index from which to return the results.
 */
offset?: number;
/**
 * 불러올 필드 이름을 쉼표로 구분하여 지정 (예: id,name,image_src)
 */
fields?: string;
};
