/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * API Documentation
 * API for my project
 * OpenAPI spec version: v1
 */

export type CrawlerSeriesEpisodeListParams = {
/**
 * 페이지 번호
 */
page?: number;
/**
 * 페이지당 항목 수 (최대 100)
 */
page_size?: number;
/**
 * 불러올 필드 이름을 쉼표로 구분하여 지정 (예: id,name,image_src)
 */
fields?: string;
/**
 * 정렬할 필드 이름을 쉼표로 구분하여 지정. '-'를 앞에 붙이면 내림차순 (예: id,-created_at,name)
 */
ordering?: string;
/**
 * 전체 에피소드 개수를 포함할지 여부 (true/false). 성능 향상을 위해 필요시에만 사용하세요.
 */
include_count?: boolean;
};
