/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * API Documentation
 * API for my project
 * OpenAPI spec version: v1
 */

export interface CustomUser {
  /**
   * @minLength 1
   * @maxLength 15
   */
  username: string;
  /** @maxLength 254 */
  email?: string;
  /**
   * @minLength 1
   * @maxLength 30
   */
  name: string;
}
