/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * API Documentation
 * API for my project
 * OpenAPI spec version: v1
 */

export interface CustomTokenObtainPair {
  /** @minLength 1 */
  access: string;
  /** @minLength 1 */
  refresh: string;
}
