/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * API Documentation
 * API for my project
 * OpenAPI spec version: v1
 */

export interface Episode {
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  id: number;
  /**
   * @minLength 1
   * @maxLength 100
   */
  name: string;
  /** @minLength 1 */
  image_src: string;
  /**
   * @minLength 1
   * @maxLength 10
   */
  category: string;
  /**
   * @minLength 1
   * @maxLength 20
   */
  subcategory: string;
  series: number;
  user: number;
}
