/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * API Documentation
 * API for my project
 * OpenAPI spec version: v1
 */
import type { Episode } from './episode';
import type { EpisodeCreateResponseErrorsItemsItem } from './episodeCreateResponseErrorsItemsItem';

export interface EpisodeCreateResponse {
  created_data: Episode[];
  errors_items: EpisodeCreateResponseErrorsItemsItem[];
}
