/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * API Documentation
 * API for my project
 * OpenAPI spec version: v1
 */

export interface TokenObtainPair {
  /** @minLength 1 */
  username: string;
  /** @minLength 1 */
  password: string;
}
